Update ci-pr-feature-to-develop-branch.yaml

diff --git a/.github/workflows/ci-pr-feature-to-develop-branch.yaml b/.github/workflows/ci-pr-feature-to-develop-branch.yaml
--- a/.github/workflows/ci-pr-feature-to-develop-branch.yaml
+++ b/.github/workflows/ci-pr-feature-to-develop-branch.yaml
@@ -1,6 +1,7 @@
 name: CI PR Feature to Main
 
 on:
+  workflow_dispatch:
   pull_request:
     branches:
       - develop
@@ -24,41 +25,41 @@ jobs:
             node-version: ${{ matrix.node-version }}
             cache: 'npm'
   
-        - name: Install MongoDB ${{ matrix.mongodb-version }}
-          uses: supercharge/mongodb-github-action@1.12.0
-          with:
-            mongodb-version: ${{ matrix.mongodb-version }}
-            mongodb-db: ${{ secrets.MONGODB_DB }}
-            mongodb-username: ${{ secrets.MONGODB_USER }}
-            mongodb-password: ${{ secrets.MONGODB_PASS }}
-            mongodb-port: 27017
+        # - name: Install MongoDB ${{ matrix.mongodb-version }}
+        #   uses: supercharge/mongodb-github-action@1.12.0
+        #   with:
+        #     mongodb-version: ${{ matrix.mongodb-version }}
+        #     mongodb-db: ${{ secrets.MONGODB_DB }}
+        #     mongodb-username: ${{ secrets.MONGODB_USER }}
+        #     mongodb-password: ${{ secrets.MONGODB_PASS }}
+        #     mongodb-port: 27017
         
-        - name: Install MongoDB shell
-          run: |
-            sudo apt-get install -y gnupg curl
-            curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
-            sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
-            --dearmor
-            echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/8.0 multiverse" | \
-            sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
-            sudo apt-get update && sudo apt-get install -y mongodb-mongosh
+        # - name: Install MongoDB shell
+        #   run: |
+        #     sudo apt-get install -y gnupg curl
+        #     curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
+        #     sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
+        #     --dearmor
+        #     echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/8.0 multiverse" | \
+        #     sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
+        #     sudo apt-get update && sudo apt-get install -y mongodb-mongosh
          
-        - name: Check MongoDB
-          run: |
-            for i in {1..30}; do
-              mongosh --eval "db.runCommand({ ping: 1 })" localhost:27017 && echo "MongoDB is up" && exit 0
-              echo "Waiting for MongoDB..."
-              sleep 2
-            done
-            echo "MongoDB did not start in time!" && exit 1
+        # - name: Check MongoDB
+        #   run: |
+        #     for i in {1..30}; do
+        #       mongosh --eval "db.runCommand({ ping: 1 })" localhost:27017 && echo "MongoDB is up" && exit 0
+        #       echo "Waiting for MongoDB..."
+        #       sleep 2
+        #     done
+        #     echo "MongoDB did not start in time!" && exit 1
         
         - name: Install dependencies
           run: npm install
   #        run: npm ci 				# Install dependencies from package-lock.json
   
         - name: Run tests
-          # run: npm test -- src/test/unit/cron-jobs/checkForLastLogin.spec.js --verbose --coverage=false 2>&1 | tee full-tests.log | tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > tests-results.txt) || true
-          run: npm test --verbose --coverage=false 2>&1 | tee full-tests.log | tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > tests-results.txt) || true
+          run: npm test -- src/test/unit/cron-jobs/checkForLastLogin.spec.js --verbose --coverage=false 2>&1 | tee full-tests.log | tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > tests-results.txt) || true
+          # run: npm test --verbose --coverage=false 2>&1 | tee full-tests.log | tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > tests-results.txt) || true
           env:
             NODE_OPTIONS: --max_old_space_size=4096
             MONGODB_URL: mongodb://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASS }}@localhost:27017/${{ secrets.MONGODB_DB }}?authSource=admin
@@ -123,28 +124,28 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   
-  container:
-    name: Check Docker Build
-    runs-on: ubuntu-latest
-    needs: run-tests
+  # container:
+  #   name: Check Docker Build
+  #   runs-on: ubuntu-latest
+  #   needs: run-tests
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
 
-      - name: Build Docker Image
-        run: |
-          docker build --tag app-test:latest .
+  #     - name: Build Docker Image
+  #       run: |
+  #         docker build --tag app-test:latest .
 
-      - name: Run Container Health Check
-        run: |
-          docker run --rm -d --name app-test-container app-test:latest
-          sleep 10
-          docker ps | grep app-test-container || exit 1
+  #     - name: Run Container Health Check
+  #       run: |
+  #         docker run --rm -d --name app-test-container app-test:latest
+  #         sleep 10
+  #         docker ps | grep app-test-container || exit 1
 
-      - name: Cleanup
-        run: |
-          docker stop app-test-container || true
+  #     - name: Cleanup
+  #       run: |
+  #         docker stop app-test-container || true
