Update ci-pr-to-develop-branch.yaml

diff --git a/.github/workflows/ci-pr-to-develop-branch.yaml b/.github/workflows/ci-pr-to-develop-branch.yaml
--- a/.github/workflows/ci-pr-to-develop-branch.yaml
+++ b/.github/workflows/ci-pr-to-develop-branch.yaml
@@ -45,28 +45,34 @@ jobs:
       - name: Check MongoDB
         run: |
           for i in {1..30}; do
-            mongosh --eval "db.runCommand({ ping: 1 })" localhost:27017 && echo "MongoDB is up" && exit 0
-            echo "Waiting for MongoDB..."
+            mongosh --eval "db.runCommand({ ping: 1 })" localhost:27017 && echo "MongoDB is up (attempt $i)" && exit 0
+            echo "Waiting for MongoDB... (attempt $i)"
             sleep 2
           done
           echo "MongoDB did not start in time!" && exit 1
 
       - name: Install dependencies
         run: npm install
-      #  run: npm ci          # TO-DO: Install dependencies from package-lock.json
+      #  run: npm ci # TO-DO: Install dependencies from package-lock.json
 
       - name: Run ESLint
         run: npm run lint:check
 
       - name: Run tests and generate logs
         run: |
-          npm run test --verbose --coverage=false 2>&1 | \
+          npm run test -- --ci --coverage=false 2>&1 | \
           # generate full-tests-results.log
-          tee "full-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" | \
+          tee "full-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log"
+          # save exit code
+          exit_code="${PIPESTATUS[0]}"
           # parsing and generate summary-tests-results.log 
-          tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > "summary-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log") | \
+          grep -E "Test Suites:|Tests:|Snapshots:|Time:" "full-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" > \
+          "summary-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log"
           # parsing and generate summary-tests-errors.log
-          tee >(awk '/Summary of all failing tests/,/Test Suites/{if ($0 !~ /Test Suites/) print}' > "summary-tests-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log") || true
+          awk '/Summary of all failing tests/,/Test Suites/{if ($0 !~ /Test Suites/) print}' "full-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" > \
+          "summary-tests-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log"
+          # enter exit code
+          exit "$exit_code"
         env:
           NODE_OPTIONS: --max_old_space_size=4096
           MONGODB_URL: mongodb://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASS }}@localhost:27017/${{ secrets.MONGODB_DB }}?authSource=admin
@@ -102,6 +108,7 @@ jobs:
 
       - name: Upload Test Logs
         uses: actions/upload-artifact@v4
+        if: success() || failure()
         with:
           name: tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}
           path: |
@@ -160,10 +167,8 @@ jobs:
             -e COOKIE_DOMAIN=${{ secrets.COOKIE_DOMAIN }} \
             --link mongodb be-app
 
-      - name: Retrieve Application Logs
-        run: docker logs be-app
-
       - name: API Health Check and Report
+        if: success() || failure()
         run: |
           sleep 10
           RESPONSE=$(curl --insecure --silent --request GET --url 'http://localhost:8080/users/')
@@ -178,6 +183,7 @@ jobs:
 
       - name: Upload Docker Health Check Results
         uses: actions/upload-artifact@v4
+        if: success() || failure()
         with:
           name: docker-health-check
           path: docker-results.log
@@ -186,12 +192,12 @@ jobs:
     name: Generate Test Report
     runs-on: ubuntu-latest
     needs: [run-tests, docker-build-test]
-    if: always()
+    if: success() || failure()
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Download Test Results
+      - name: Download Tests Results
         uses: actions/download-artifact@v4
         with:
           path: test-reports
@@ -205,49 +211,53 @@ jobs:
       - name: Generate Test Report
         run: |
           CI_MARKER="### ✅ CI Report - $(TZ="Europe/Kyiv" date +"%H:%M %d/%m/%Y")"
-          echo "$CI_MARKER" > test-report.txt
-          echo "" >> test-report.txt
+          {
+            echo "$CI_MARKER"
+            echo ""
+          } > test-report.txt
 
           for folder in test-reports/tests-results-*; do
             TEST_VERSION=$(basename "$folder")
             NODE_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f3)
             MONGO_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f4)
-            
+
             SUMMARY_FILE="test-reports/tests-results-${NODE_VERSION}-${MONGO_VERSION}/summary-tests-results-${NODE_VERSION}-${MONGO_VERSION}.log"
             ERRORS_FILE="test-reports/tests-results-${NODE_VERSION}-${MONGO_VERSION}/summary-tests-errors-${NODE_VERSION}-${MONGO_VERSION}.log"
-            
-            echo "**🔹 Node.js Version:** $NODE_VERSION" >> test-report.txt
-            echo "**🔹 MongoDB Version:** $MONGO_VERSION" >> test-report.txt
-            echo "" >> test-report.txt
-            
-            echo "### 🧪 Test Results" >> test-report.txt
-            echo '```' >> test-report.txt
-            cat "$SUMMARY_FILE" >> test-report.txt
-            echo '```' >> test-report.txt
-            echo "" >> test-report.txt
-            
-            if [[ -s "$ERRORS_FILE" ]]; then
-              echo "### ❌ Test Errors" >> test-report.txt
-              echo '```' >> test-report.txt
-              cat "$ERRORS_FILE" >> test-report.txt
-              echo '```' >> test-report.txt
-            fi
-            echo "" >> test-report.txt
+
+            {
+              echo "**🔹 Node.js Version:** $NODE_VERSION"
+              echo "**🔹 MongoDB Version:** $MONGO_VERSION"
+              echo ""
+              echo "### 🧪 Test Results"
+              echo '```'
+              cat "$SUMMARY_FILE"
+              echo '```'
+
+              if [[ -s "$ERRORS_FILE" ]]; then
+                echo "### ❌ Test Errors"
+                echo '```'
+                cat "$ERRORS_FILE"
+                echo '```'
+              fi
+
+              printf "\n"
+            } >> test-report.txt
           done
 
           DOCKER_LOG="test-reports/docker-results.log"
           if [[ -f "$DOCKER_LOG" ]]; then
-            echo "### 🐳 Docker Health Check Results" >> test-report.txt
-            echo '```' >> test-report.txt
-            cat "$DOCKER_LOG" >> test-report.txt
-            echo '```' >> test-report.txt
+            {
+              echo "### 🐳 Docker Health Check Results"
+              echo '```'
+              cat "$DOCKER_LOG"
+              echo '```'
+            } >> test-report.txt
           else
-            echo "### 🐳 Docker Health Check Results" >> test-report.txt
-            echo "**No Docker health check results found.**" >> test-report.txt
+            echo -e "### 🐳 Docker Health Check Results\n**No Docker health check results found.**" >> test-report.txt
           fi
 
       - name: Publish Report in GitHub Actions Summary
-        run: cat test-report.txt >> $GITHUB_STEP_SUMMARY
+        run: cat test-report.txt >> "$GITHUB_STEP_SUMMARY"
 
       - name: Update CI Report in PR
         env:
@@ -259,12 +269,12 @@ jobs:
             exit 0
           fi
 
-          COMMENT_ID=$(gh api repos/:owner/:repo/issues/$PR_NUMBER/comments --jq '.[] | select(.user.login=="github-actions[bot]") | select(.body | contains("### ✅ CI Report")) | .id')
+          COMMENT_ID=$(gh api "repos/:owner/:repo/issues/$PR_NUMBER/comments" --jq '.[] | select(.user.login=="github-actions[bot]") | select(.body | contains("### ✅ CI Report")) | .id')
 
           if [[ -n "$COMMENT_ID" ]]; then
             echo "Updating existing CI report comment: $COMMENT_ID"
-            gh api repos/:owner/:repo/issues/comments/$COMMENT_ID -X PATCH -f body="$(cat test-report.txt)"
+            gh api "repos/:owner/:repo/issues/comments/$COMMENT_ID" -X PATCH -f body="$(cat test-report.txt)"
           else
             echo "No previous CI report found, creating a new one..."
-            gh pr comment $PR_NUMBER --body-file test-report.txt
+            gh pr comment "$PR_NUMBER" --body-file "test-report.txt"
           fi
