- Updated "Run tests and generate logs" job - Added test results upload on failure - Added Docker health check results upload on failure - Added report generation on job failure

diff --git a/.github/workflows/ci-pr-to-develop-branch.yaml b/.github/workflows/ci-pr-to-develop-branch.yaml
--- a/.github/workflows/ci-pr-to-develop-branch.yaml
+++ b/.github/workflows/ci-pr-to-develop-branch.yaml
@@ -53,20 +53,26 @@ jobs:
 
       - name: Install dependencies
         run: npm install
-      #  run: npm ci          # TO-DO: Install dependencies from package-lock.json
+      #  run: npm ci # TO-DO: Install dependencies from package-lock.json
 
       - name: Run ESLint
         run: npm run lint:check
 
       - name: Run tests and generate logs
         run: |
-          npm run test --verbose --coverage=false 2>&1 | \
+          npm run test -- --ci --coverage=false 2>&1 | \
           # generate full-tests-results.log
-          tee "full-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" | \
+          tee "full-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log"
+          # save exit code
+          exit_code="${PIPESTATUS[0]}"
           # parsing and generate summary-tests-results.log 
-          tee >(grep -E "Test Suites:|Tests:|Snapshots:|Time:" > "summary-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log") | \
+          grep -E "Test Suites:|Tests:|Snapshots:|Time:" "full-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" > \
+          "summary-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log"
           # parsing and generate summary-tests-errors.log
-          tee >(awk '/Summary of all failing tests/,/Test Suites/{if ($0 !~ /Test Suites/) print}' > "summary-tests-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log") || true
+          awk '/Summary of all failing tests/,/Test Suites/{if ($0 !~ /Test Suites/) print}' "full-tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log" > \
+          "summary-tests-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log"
+          # enter exit code
+          exit "$exit_code"
         env:
           NODE_OPTIONS: --max_old_space_size=4096
           MONGODB_URL: mongodb://${{ secrets.MONGODB_USER }}:${{ secrets.MONGODB_PASS }}@localhost:27017/${{ secrets.MONGODB_DB }}?authSource=admin
@@ -102,6 +108,7 @@ jobs:
 
       - name: Upload Test Logs
         uses: actions/upload-artifact@v4
+        if: success() || failure()
         with:
           name: tests-results-${{ matrix.node-version }}-${{ matrix.mongodb-version }}
           path: |
@@ -160,9 +167,6 @@ jobs:
             -e COOKIE_DOMAIN=${{ secrets.COOKIE_DOMAIN }} \
             --link mongodb be-app
 
-      - name: Retrieve Application Logs
-        run: docker logs be-app
-
       - name: API Health Check and Report
         run: |
           sleep 10
@@ -178,6 +182,7 @@ jobs:
 
       - name: Upload Docker Health Check Results
         uses: actions/upload-artifact@v4
+        if: success() || failure()
         with:
           name: docker-health-check
           path: docker-results.log
@@ -186,12 +191,12 @@ jobs:
     name: Generate Test Report
     runs-on: ubuntu-latest
     needs: [run-tests, docker-build-test]
-    if: always()
+    if: success() || failure()
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Download Test Results
+      - name: Download Tests Results
         uses: actions/download-artifact@v4
         with:
           path: test-reports
