Update ci-push-feature-bugfix-chore.yaml

diff --git a/.github/workflows/ci-push-feature-bugfix-chore.yaml b/.github/workflows/ci-push-feature-bugfix-chore.yaml
--- a/.github/workflows/ci-push-feature-bugfix-chore.yaml
+++ b/.github/workflows/ci-push-feature-bugfix-chore.yaml
@@ -31,6 +31,7 @@ jobs:
 
       - name: Upload Lint.log
         uses: actions/upload-artifact@v4
+        if: success() || failure()
         with:
           name: lint.log
           path: |
@@ -164,76 +165,59 @@ jobs:
             # summary-tests-errors.log
             summary-tests-errors-${{ matrix.node-version }}-${{ matrix.mongodb-version }}.log
 
-  generate-tests-report:
-    name: Generate Report with tests results
+  generate-report:
+    name: Generate CI Report
     runs-on: ubuntu-latest
     needs: ['check-skip-tests', 'run-tests']
-    if: needs.check-skip-tests.outputs.skip-tests == 'false'
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Download Test Results
+      - name: Download Test Results (if tests were run)
+        if: needs.check-skip-tests.outputs.skip-tests == 'false'
         uses: actions/download-artifact@v4
         with:
           path: test-reports
 
-      - name: Generate Test Report
+      - name: Generate Report
         run: |
           CI_MARKER="### ✅ CI Report - $(TZ="Europe/Kyiv" date +"%H:%M %d/%m/%Y")"
           echo "$CI_MARKER" > test-report.txt
           echo "" >> test-report.txt
 
-          for folder in test-reports/tests-results-*; do
-            TEST_VERSION=$(basename "$folder")
-            NODE_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f3)
-            MONGO_VERSION=$(echo "$TEST_VERSION" | cut -d'-' -f4)
-            
-            SUMMARY_FILE="test-reports/tests-results-${NODE_VERSION}-${MONGO_VERSION}/summary-tests-results-${NODE_VERSION}-${MONGO_VERSION}.log"
-            ERRORS_FILE="test-reports/tests-results-${NODE_VERSION}-${MONGO_VERSION}/summary-tests-errors-${NODE_VERSION}-${MONGO_VERSION}.log"
-            
-            echo "**🔹 Node.js Version:** $NODE_VERSION" >> test-report.txt
-            echo "**🔹 MongoDB Version:** $MONGO_VERSION" >> test-report.txt
-            echo "" >> test-report.txt
-            
+          if [[ "${{ needs.check-skip-tests.outputs.skip-tests }}" == "false" ]]; then
+            for folder in test-reports/tests-results-*; do
+              NODE_VERSION=$(echo "$folder" | awk -F'-' '{print $3}')
+              MONGO_VERSION=$(echo "$folder" | awk -F'-' '{print $4}')
+              
+              SUMMARY_FILE="$folder/summary-tests-results-${NODE_VERSION}-${MONGO_VERSION}.log"
+              ERRORS_FILE="$folder/summary-tests-errors-${NODE_VERSION}-${MONGO_VERSION}.log"
+
+              echo "**🔹 Node.js Version:** $NODE_VERSION" >> test-report.txt
+              echo "**🔹 MongoDB Version:** $MONGO_VERSION" >> test-report.txt
+              echo "" >> test-report.txt
+
+              echo "### 🧪 Test Results" >> test-report.txt
+              echo '```' >> test-report.txt
+              cat "$SUMMARY_FILE" >> test-report.txt
+              echo '```' >> test-report.txt
+              echo "" >> test-report.txt
+
+              if [[ -s "$ERRORS_FILE" ]]; then
+                echo "### ❌ Test Errors" >> test-report.txt
+                echo '```' >> test-report.txt
+                cat "$ERRORS_FILE" >> test-report.txt
+                echo '```' >> test-report.txt
+              fi
+              echo "" >> test-report.txt
+            done
+          else
             echo "### 🧪 Test Results" >> test-report.txt
             echo '```' >> test-report.txt
-            cat "$SUMMARY_FILE" >> test-report.txt
+            echo "Tests were skipped due to [devops] or [docs] commit flag." >> test-report.txt
             echo '```' >> test-report.txt
             echo "" >> test-report.txt
-            
-            if [[ -s "$ERRORS_FILE" ]]; then
-              echo "### ❌ Test Errors" >> test-report.txt
-              echo '```' >> test-report.txt
-              cat "$ERRORS_FILE" >> test-report.txt
-              echo '```' >> test-report.txt
-            fi
-            echo "" >> test-report.txt
-          done
-
-      - name: Publish Report in GitHub Actions Summary
-        run: cat test-report.txt >> $GITHUB_STEP_SUMMARY
-
-  generate-report:
-    name: Generate Report without tests results
-    runs-on: ubuntu-latest
-    needs: ['check-skip-tests']
-    if: needs.check-skip-tests.outputs.skip-tests == 'true'
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Generate report
-        run: |
-          CI_MARKER="### ✅ CI Report - $(TZ="Europe/Kyiv" date +"%H:%M %d/%m/%Y")"
-          echo "$CI_MARKER" > test-report.txt
-          echo "" >> test-report.txt
-
-          echo "### 🧪 Test Results" >> test-report.txt
-          echo '```' >> test-report.txt
-          echo "Tests were skipped because the commit message contained a skip flag ([devops] or [docs])." >> test-report.txt
-          echo '```' >> test-report.txt
-          echo "" >> test-report.txt
+          fi
 
       - name: Publish Report in GitHub Actions Summary
         run: cat test-report.txt >> $GITHUB_STEP_SUMMARY
