Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -42,7 +42,7 @@ jobs:
         run: npm install
         
       - name : 'Run Tests'
-        run: npm run test
+        run: npm test -- src/test/unit/services --verbose --coverage=false
         env:
           NODE_OPTIONS: --max_old_space_size=4096
           MONGODB_URL: mongodb://${{secrets.MONGODB_USER}}:${{secrets.MONGODB_PASS}}@localhost:27017/${{secrets.MONGODB_DB}}?authSource=admin
@@ -68,24 +68,24 @@ jobs:
           GMAIL_REFRESH_TOKEN: ${{secrets.GMAIL_REFRESH_TOKEN}}
           GMAIL_REDIRECT_URI: ${{secrets.GMAIL_REDIRECT_URI}}
           COOKIE_DOMAIN: ${{secrets.COOKIE_DOMAIN}}
-      # Sonar    
-      - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@master
-        if: success() || failure()
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#     # Sonar    
+#     - name: SonarCloud Scan
+#       uses: SonarSource/sonarcloud-github-action@master
+#       if: success() || failure()
+#       env:
+#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-  Test_Docker:
-    runs-on: ubuntu-latest
-    steps:
+# Test_Docker:
+#   runs-on: ubuntu-latest
+#   steps:
 
-      #Checkout Repository
-      - uses: actions/checkout@v3
-      
-      # Docker Build
-      - uses: docker/build-push-action@v3
-        with:
-          push: false
-          file: ./Dockerfile
-          tags: back-stage:test
+#     #Checkout Repository
+#     - uses: actions/checkout@v3
+#     
+#     # Docker Build
+#     - uses: docker/build-push-action@v3
+#       with:
+#         push: false
+#         file: ./Dockerfile
+#         tags: back-stage:test
